name       : barrier
version    : 2.4.0
release    : 6
source     :
    - git|https://github.com/debauchee/barrier.git : dc7aa012d5b6b5b57bd81f571795baf0cde9049e
license    : GPL-2.0-or-later
homepage   : https://github.com/debauchee/barrier
component  : network.util
summary    : KVM software allowing you to share your mouse and keyboard between multiple computers, an opensource fork of synergy
description: |
    KVM software allowing you to share your mouse and keyboard between multiple computers, an opensource fork of synergy
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(avahi-core)
    - pkgconfig(libcurl)
    - pkgconfig(sm)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -dm00644 $installdir/usr/share/man/man1
    mv doc/*.1 $installdir/usr/share/man/man1/
    install -dm00644 $installdir/usr/share/doc/barrier
    mv doc/barrier.conf* $installdir/usr/share/doc/barrier/
