name       : barrier
version    : 2.3.2
release    : 2
source     :
    - https://github.com/debauchee/barrier/archive/v2.3.2.tar.gz : 6b92a70c5f4d625065842d133386982ec2ad1db2a809af47e46ab8ce2acd39b5
license    : GPL-2.0-or-later
component  : network.util
summary    : KVM software allowing you to share your mouse and keyboard between multiple computers, an opensource fork of synergy
description: |
    KVM software allowing you to share your mouse and keyboard between multiple computers, an opensource fork of synergy
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(avahi-core)
    - pkgconfig(libcurl)
    - pkgconfig(sm)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -dm00644 $installdir/usr/share/man/man1
    mv doc/*.1 $installdir/usr/share/man/man1/
    install -dm00644 $installdir/usr/share/doc/barrier
    mv doc/barrier.conf* $installdir/usr/share/doc/barrier/
